### ISSUE TITLE
Missing host parameter while loading

### ISSUE THREAD

**Issue by Mc128k** [AngularClass/angular2-seed#12]
I noticed in the webpack.config.ts file that the following lines are missing, and make modifications to the hostname ineffective:

```
devServer: {
      contentBase: './src',
      port: CONSTANTS.PORT,
// ADD THIS
      host: CONSTANTS.HOST,
 
      hot: CONSTANTS.HMR,
      inline: CONSTANTS.HMR,
      historyApiFallback: true
    },
````

and after that...

```
  devServer?: {
    contentBase?: string;
    port?: number;
    historyApiFallback?: boolean;
    hot?: boolean;
    inline?: boolean;

// ADD THIS
    host?: string;
  };
```

That fixes the parameter not being read

**Comment by Meligy** [comment]
I just discovered the same today at work as well.

Will work on a PR.

**Comment by gdi2290** [comment]
thanks, closed via https://github.com/AngularClass/angular2-seed/pull/13
