### ISSUE TITLE
[Bug] Validation is not working in /about route

### ISSUE THREAD

**Issue by Meligy** [AngularClass/angular2-seed#15]
> Same across Windows and Mac

## To Reproduce

0. First run in *nix OS or ensure PR #14 is applied for Windows
1. Ensure you go latest git repo, and run `npm install` to validate dependencies as well
2. Run `npm start`
3. In browser, navigate to "#/about"
4. Open the console
5. Enter non email value in the input field ("asd" or whatever)
6. Click the submit button

## Actual Result

You'll notice the console is writing the form value, and no validation error message is showing, 

## Expected Result

According to the component code, it should write `form invalid` to the console, and show validation message `Please use a valid email address` on the page.

**Comment by gdi2290** [comment]
I need to update the module to use rc5

**Comment by gdi2290** [comment]
done via https://github.com/AngularClass/angular2-seed/commit/8fe9cd19430f96b7333ad54ac90320206b8a7cae
