### ISSUE TITLE
npm run build ERROR

### ISSUE THREAD

**Issue by Enlcxx** [AngularClass/angular2-seed#16]
D:\xampp.v.56\htdocs\headexpeditionsA2>npm run build

> angular2-seed@0.0.0 prebuild D:\xampp.v.56\htdocs\headexpeditionsA2
> rm -rf dist

"rm" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Users\\Fx-Enlcxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v5.7.0
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 prebuild: `rm -rf dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 prebuild script 'rm -rf dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\xampp.v.56\htdocs\headexpeditionsA2\npm-debug.log

**Comment by Meligy** [comment]
That seems to be lack of `rm` command on Windows.

Common workarounds seem to be a specific npm package [rimraf](https://www.npmjs.com/package/rimraf), or a general cross-platform shell package like [shelljs](https://www.npmjs.com/package/shelljs).

Not sure which approach @gdi2290 would prefer.

**Comment by gdi2290** [comment]
this has been updated thanks
