### ISSUE TITLE
Align file names with angular-cli (nice to have)

### ISSUE THREAD

**Issue by mmrath** [AngularClass/angular2-seed#19]
It would be nice to get the file names in the src folder more aligned to angular-cli.

**Comment by gdi2290** [comment]
thanks for creating issues with feedback.  while it seems like a good idea the current conventions, for the cli, introduces a ton of boilerplate and namespacing that I'm not a fan of

**Comment by Meligy** [comment]
Is this worth waiting about in readme or new wiki FAQ page?

Thanks :)
