### ISSUE TITLE
(minor issue) Type 'Type' is not generic.

### ISSUE THREAD

**Issue by mmrath** [AngularClass/angular2-seed#21]
[default] C:\Projects\angular2-seed\node_modules\@angular\router\src\config.d.ts:252:64
    Type 'Type' is not generic.
[default] Checking finished with 1 errors

**Comment by gdi2290** [comment]
thanks, fixed via https://github.com/gdi2290/router-builds/commit/41c6a722c6cf02e632b4446f40d18e51fa0ed4a0
