### ISSUE TITLE
npm start fails on windows (server:dev script issue)

### ISSUE THREAD

**Issue by j3ddesign** [AngularClass/angular2-seed#5]
Windows doesn't like running the following:
`"server:dev": "node_modules/webpack-dev-server/bin/webpack-dev-server.js --env.ENV development",` 

I had to change this to `"server:dev": "webpack-dev-server --env.ENV development",`

**Comment by gdi2290** [comment]
should be fix via https://github.com/AngularClass/angular2-seed/commit/4a11b79ef85bff19e58059e140c77603cbfd085d
